language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
  #TODO add pypy
# command to install dependencies
install:
- pip install -e .
- pip install -r requirements.txt


before_script:
- ls
- pwd

script:
- nosetests
- cd pytorrent && nosetests && cd ..
- python pytorrent/tests/unitest.py

matrix:
  allow_failures:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5.0b3"
    - "3.5-dev"
    - "nightly"
