language: python
python:
  - "2.6"
  - "2.7"
  #TODO add pypy
# command to install dependencies
install: 
- pip install -e .
- pip install bencode



before_script:
- ls
- pwd

script: 
- nosetests
- python pytorrent/tests/unitest.py
